version: '2.4'

networks:
  # Required for the devcontainer
  entrust_network:
    name: entrust_network

services:
  entrust_influx_db:
    extends:
      file: docker-compose.databases.yml
      service: entrust_influx_db
    networks:
      - entrust_network
    ports:
      - '8086:8086'

  entrust_neo4j_kg:
    extends:
      file: docker-compose.databases.yml
      service: entrust_neo4j_kg
    networks:
      - entrust_network
    ports:
      - 7474:7474
      - 7687:7687

  entrust_minio_s3:
    extends:
      file: docker-compose.databases.yml
      service: entrust_minio_s3
    networks:
      - entrust_network
    ports:
      - "9000:9000"
      - "9099:9099"

  zookeeper:
    image: 'zookeeper:3.7'
    networks:
      - entrust_network
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    networks:
      - entrust_network
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mqtt_kafka_bridge:
    image: mqtt-kafka-bridge
    depends_on:
      - kafka
    networks:
      - entrust_network


volumes:
  entrust-minio-s3-volume:
  entrust-neo4j-conf-volume:
  entrust-neo4j-logs-volume:
  entrust-neo4j-data-volume:
  entrust-influx-db-data-volume:
  entrust-influx-db-config-volume:
  entrust-kafka-data-volume:
